version: "3"

services:

  db:
    image: "postgres:12"
    container_name: "exposed-enum-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "exposed-enum-db"
    volumes:
      - ./exposed-enum-db:/var/lib/postgresql/data
